[project]
name = "smolagents-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "googlemaps>=4.10.0",
    "python-dotenv>=1.0.1",
    "smolagents[litellm,transformers]>=1.5.0",
]
